"""add path_origin field to documents

Revision ID: c2404770ca78
Revises: 0001_init
Create Date: 2025-08-27 11:41:59.331975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2404770ca78'
down_revision: Union[str, Sequence[str], None] = '0001_init'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('path_origin', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_documents_search_vector'), 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    # op.create_index(op.f('ix_documents_content_trgm'), 'documents', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('documents', 'path_origin')
    # ### end Alembic commands ###
