"""add column email to Document (3)

Revision ID: ce3b14b411ca
Revises: 2ae72d418ad5
Create Date: 2025-09-23 17:00:52.548960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3b14b411ca'
down_revision: Union[str, Sequence[str], None] = '2ae72d418ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'email')
    # ### end Alembic commands ###
